-- phpMyAdmin SQL Dump
-- version 3.5.8.1
-- http://www.phpmyadmin.net
--
-- Machine: localhost:3306
-- Genereertijd: 23 apr 2014 om 16:30
-- Serverversie: 5.1.73
-- PHP-versie: 5.3.10

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Databank: `ipmedt4groep1`
--

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `opdrachtgevers`
--

CREATE TABLE IF NOT EXISTS `opdrachtgevers` (
  `pid` int(20) NOT NULL AUTO_INCREMENT,
  `naam` varchar(50) NOT NULL,
  `beschrijving` varchar(750) NOT NULL,
  `website` varchar(100) NOT NULL,
  `logo_full` varchar(255) NOT NULL,
  PRIMARY KEY (`pid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=17 ;

--
-- Gegevens worden uitgevoerd voor tabel `opdrachtgevers`
--

INSERT INTO `opdrachtgevers` (`pid`, `naam`, `beschrijving`, `website`, `logo_full`) VALUES
(1, 'Area071', 'De initiatiefnemers van Area071 is een tweetal ervaren ondernemers; Arjan Meester en Bart Hoenen.\n\nGezamenlijk vormen zij de directie van AREA071. Geen directie op afstand maar direct en in het hart van het concept. Ook zij staan dagelijks de starters met advies en ondersteuning bij in het vervullen van hun eigen droom. Een directie die hun eigen niet aflatende behoefte naar ondernemerschap, durf en creativiteit leidend laat zijn voor de uitvoering van dit verhaal.', 'www.area071.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_Area071.jpg'),
(2, 'Leids Lekkers', 'LeidsLekkers, lokaal genieten! \n\nMet meer dan 100 culinaire adressen is LeidsLekkers het platform voor lekker eten en drinken in Leiden en omgeving. Een platform waar gast en restaurateur samenkomen door middel van informatie, recensies, een jaarlijks terugkerende Leidse Restaurantweek en overige culinaire evenementen.\n\nLeidsLekkers organiseert jaarlijks diverse lokale evenementen, waarbij lokaal en culinair centraal staan. Evenementen als opening van het terrassenseizoen, museum culinair, running dinner by boat en onze jaarlijkse Leidse Restaurantweek. Volop lokaal genieten dus! \n', 'www.leidslekkers.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_LeidsLekkers.png'),
(3, 'Swets', 'Swets is wereldwijd toonaangevend op het gebied van professioneel informatiebeheer. Wij ontwikkelen en leveren vernieuwende diensten voor contentbeheer voor bibliotheken en uitgevers, waardoor kennis ten volle benut kan worden. We hebben meer dan 20 kantoren over de hele wereld waarvandaan we klanten en uitgevers helpen in meer dan 160 landen. Wij zijn een onderdeel van Swets Information Services.', 'www.swets.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_Swets.png'),
(4, 'Unity FM', 'Unity FM is de radio zender van de lokale omroep voor Leiden, Leiderdorp, Zoeterwoude, Voorschoten en Oegstgeest. In de regio Leiden is Unity te ontvangen op 105.7 FM. Ook via Ziggo digitaal kanaal 780 kun je naar Unity FM luisteren. Ook is de zender op de kabel te horen als geluid achter Unity TV.\n\nIn de regio Leiden wordt Unity FM geproduceerd door Rudeboy Media in opdracht van Stichting Agglomeratie Omroep Holland Centraal. Dit gebeurt sinds september 2009. (Voorheen gebeurde dit onder de naam Holland Centraal)\n', 'www.unityfm.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_UnityFM.jpg'),
(5, 'Vincentius Hof', 'Vincentius'' Hof is een centrum van ontmoeting en inspiratie en wil met inzet van vrijwilligers en medewerkers voor al zijn bezoekers zijn:\n\nEen herberg waar mensen elkaar willen ontmoeten, een thuis vinden, op verhaal komen;\n\nEen tempel waar mensen zich herkend en erkend weten naar hun eigen tradities in respect voor ieders spirituele achtergrond;\n\nEen school waar mensen van elkaar willen leren in een proces van geven en ontvangen;\n\nVincentius'' Hof staat open voor alle mensen die in Den Haag wonen en werken, met speciale aandacht voor hen die op zoek zijn naar nieuwe kansen.\n', 'www.vincentiushof.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_VincentiusHof.jpg'),
(6, 'Stichting Present', 'Wie is Present?\nPresent slaat een brug tussen mensen die iets hebben te bieden en mensen die daarmee geholpen kunnen worden. Zo willen we bouwen aan een samenleving waarbij mensen het vanzelfsprekend vinden om naar elkaar om te zien.  \n\nWaarom Present?\nMensen zijn bereid iets voor anderen te betekenen. De vraag is: hoe doe je dat? En wie is verantwoordelijk voor welke zorg. De samenleving is complex en veranderd. Ondertussen staat een grote groep mensen aan de rand van de samenleving.  \n', 'www.stichtingpresent.nl/', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo+StichtingPresent.jpg'),
(7, 'Naturalis Biodiversity Center', 'Bij Naturalis Biodiversity Center willen we biodiversiteit beschrijven, begrijpen en verklaren. Voor het welzijn van de mens en het voortbestaan van de aardse natuur.', 'www.naturalis.nl ', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_Naturalis.jpg'),
(8, 'Hutspop', 'Hutspop is een jaarlijks muzikaal evenement in de binnenstad van Leiden. In tegenstelling tot evenementen waar bestaande bands optreden, is Hutspop ook een competitieve uitdaging voor individuele muzikanten uit heel Nederland. \n\nDe bands worden door middel van een trekking samengesteld uit de ingeschreven muzikanten die per categorie (instrument) ingedeeld worden. Zo ook het repertoire dat zij moeten spelen op Hutspop. Onder begeleiding van een bandcoach krijgen de bands 8 weken de tijd om een echte band te worden die voor dat grote publiek een knallend optreden neerzet. Zowel op muzikaal als sociaal gebied een grote uitdaging.', 'www.hutspop.org', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_Hutspop.jpg'),
(9, 'Gordijn', 'Aannemersbedrijf Gordijn, te Hazerswoude-dorp, is een aannemersbedrijf dat werkzaamheden aanneemt, uitvoert en coordineert op het gebied van nieuwbouw, verbouw, onderhoud, renovatie en betonwerk.', 'www.aannemersbedrijfgordijn.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_Gordijn.gif'),
(10, 'The Art Shop', 'The Art Shop is een kunstgalerie waar iedereen welkom is. U kunt terecht bij een van onze drie vestigingen of, u neemt een kijkje op onze site. De collectie bevat een ruime keuze aan diverse kunstwerken van nationaal en internationaal bekende, maar ook minder bekende kunstenaars. \n\nThe Art Shop heeft als doel kunst toegankelijk te maken voor een breed publiek, van jong tot oud en de collectie bestaat uit een uitgebreide en gevarieerde verzameling moderne kunst met originelen, grafiek en sculpturen van kunstenaars zoals bijvoorbeeld: Herman Brood, Jacqueline Schafer, Ronald Chapeau, Peter Klashorst, Guy Olivier, Floyd Douglas, Yulia Muravyeva, Espen Hagen, Anton Heyboer en anderen. ', 'www.theartshop.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_ TheArtshop.png'),
(11, 'Acoustic Alley', 'Acoustic Alley is een initiatief van Frank Bukkems en Marlies Willemsen. Als liefhebbers van singersongwriters en Americana misten zij een geschikte locatie in de regio Den Haag voor dergelijke muziek. Zij ontdekten dat zij niet de enigen waren en besloten om een podium op te zetten waar artiesten kleinschalige, intieme concerten konden geven. Theater In de Steeg aan het Haagse Westeinde bleek een geschikte locatie voor hun plannen en op 5 oktober 2003 startte het eerste seizoen Acoustic Alley.\n\n', 'www.acousticalley.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_AcousticAlley.png'),
(12, 'Be Silk', 'Be Silk is uw specialist om uw gehele lichaam te ontharen. Zowel voor mannen als vrouwen bieden wij behandelingen aan, afgestemd op uw specifieke wensen.\n\nOf u met zijdezachte, gladde benen de zomer in wilt gaan, uw intieme zones hygienisch wilt laten ontharen of van ontsierende haren in uw gezicht af wilt, Be Silk is uw betrouwbare partner om ongewenste haargroei te verwijderen.\n\nOnze specialisatie is ontharen. Door onze jarenlange ervaring zijn wij het meest enthousiast over waxen met suiker: het zogenaamde suikeren. Daarmee krijgt u die begeerlijke, gezonde huid, zonder ontsierende, stekelige stoppeltjes, bultjes of ingegroeide haren. Wij gebruiken uitsluitend suiker en lotions, die aan onze hoge kwaliteitseisen voldoet.', 'www.besilk.nl ', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_Be_Silk.png'),
(13, 'BplusC', 'Vanaf 2008 zijn Bibliotheken Leiden & Leiderdorp, Leidse Volksuniversiteit K&O, Het Leidse Volkshuis, Muziekschool Leiden en Omstreken samen verder gegaan onder de naam Bibliotheek plus Centrum voor kunst en cultuur, kortweg BplusC. \n\nBplusC is een dynamische organisatie die iedereen in Leiden, Leiderdorp, Oegstgeest, Voorschoten en Wassenaar een mooi, veelzijdig en compleet aanbod biedt. Onder het motto een leven lang leren zorgen wij voor een programma vol kennis, ontwikkeling, maatschappij, kunst en cultuur. ', 'www.bplusc.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_BplusC.png'),
(14, 'Esthetica Schoonheidssalon', 'Heeft u een druk bestaan waardoor u soms even lekker tot rust wil komen? Geniet dan eens van een of meerdere behandelingen bij Schoonheidssalon Esthetica in Hazerswoude.\n\nWat maakt onze salon uniek?\n\nOnze salon beschikt over de meest revolutionaire technieken met betrekking tot het verwijderen van cellulitis\n\nWij werken samen met professionals zoals een huidtherapeut en een cosmetisch arts voor injectables en fillers\n\nWij zijn de enige salon in de wijde omtrek die de Bergman Beauty Care productlijn mag voeren; zodat u verzekert bent van de beste anti aging producten.', 'www.schoonheidssalonesthetica.com', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_Esthetica.png'),
(15, 'Gemeente Leiden', '', 'www.leiden.nl/gemeente', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_Gemeente Leiden.jpg'),
(16, 'Pauline Assisteert', '', 'www.paulineassisteert.nl', 'http://www.jellescheer.nl/logo/opdrachtgevers/Logo_PaulineAssisteert.jpg');

-- --------------------------------------------------------

--
-- Tabelstructuur voor tabel `studentenbedrijfjes`
--

CREATE TABLE IF NOT EXISTS `studentenbedrijfjes` (
  `pid` int(20) NOT NULL AUTO_INCREMENT,
  `naam` varchar(500) NOT NULL,
  `deelnemers` varchar(150) NOT NULL,
  `opdrachtgever` varchar(50) NOT NULL,
  `soort` varchar(100) NOT NULL,
  `beschrijving` varchar(1000) NOT NULL,
  `website` varchar(200) NOT NULL,
  `likes` int(200) NOT NULL,
  `stemmen` int(255) NOT NULL,
  `logo_full` varchar(150) NOT NULL,
  PRIMARY KEY (`pid`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=21 ;

--
-- Gegevens worden uitgevoerd voor tabel `studentenbedrijfjes`
--

INSERT INTO `studentenbedrijfjes` (`pid`, `naam`, `deelnemers`, `opdrachtgever`, `soort`, `beschrijving`, `website`, `likes`, `stemmen`, `logo_full`) VALUES
(1, 'Bureau 5', '- Rady Atia Hassan\n- Helena Pel\n- Susanne van Schaik\n- Isabel Nikolov\n- Mandy van Mullen', 'The Art Shop', 'Marketing & Communicatie', 'Bureau 5 is een marketing communicatie bureau die op een creatieve en vernieuwende wijze uw diensten of producten positioneert en naamsbekendheid genereert. Ieder lid van bureau 5 deelt dezelfde visie namelijk communicatie gaat verder dan de wereld. \n\nBureau 5 bestaat uit vijf jonge, ambitieuze studenten die verder durven te dromen en risicos durven te nemen. Dit wordt doorgezet in alle facetten van het bureau. Door het hanteren van creatieve denktechnieken en vernieuwende activiteiten heeft bureau 5 een frisse blik op uw ideeen. \n\nBureau 5 houdt zich bezig met Positionering en Promotie. ', 'www.bureau5.nl', 7, 16, 'http://www.jellescheer.nl/logo/full/Logo_Bureau5.jpg'),
(2, 'Complete', '- Bas Boswinkel\n- Martijn van Duijvenbode\n- Jaimy Fokkens\n- Iris Formanoij\n- Nicole Gabrielse', 'Acoustic Alley', 'Marketing & Communicatie', 'Complete is een bureau bestaande uit 5 jonge, enthousiaste communicatiestudenten. Met een team bestaande uit 3 mannen en 2 vrouwen vormen wij een zeer goed uitgebalanceerd team. \n\nComplete brengt alle vormen van communicatie samen tot een lopend geheel. Wij bedenken en onderzoeken welke vormen aanslaan bij de doelgroep en hoe deze het best ingezet kunnen worden. Zou houden wij ons bezig met Social Media advies, Online marketingadvies, Marketingcommunicatieadvies, Grafisch Design, Marktonderzoek, Positioneringsadvies en Corporate Identity. ', 'http://oege.ie.hva.nl/~beerend001/complete/', 115, 10, 'http://www.jellescheer.nl/logo/full/Logo_Complete.jpg'),
(3, 'Echt', '- Sofie van der Marel\n- Eline Koetsier\n- Lianne de Kok\n- Niels Buijs\n- Frouke Kuijf', 'Naturalis', 'Communicatiebureau', 'Wie zijn wij: Echt. Communicatie bestaat uit vijf hardwerkende studenten aan de Hogeschool Leiden. Allemaal jonge frisse studenten die klaar zijn voor een uitdaging. \n \nEcht. Communicatie is gespecialiseerd in Public Relations, Promotie en Positionering van product, merk of dienst.', 'http://echtcommunicatie.wix.com/echt-communicatie', 2, 4, 'http://www.jellescheer.nl/logo/full/Logo_Echt.png'),
(4, 'Experienca', '- Avanaisa Mbelle Dipenda\n- Dianne Overbeek\n- Francis Mekhail\n- Maaike Lut\n- Miquel Simons', 'Leids Lekkers (Lawrence Armitage)', 'Reclamebureau', 'Experienca is een jong en dynamisch bedrijf. Onze enthousiaste medewerkers zijn tweedejaarsstudenten in het communicatie vak en kunnen de nieuwste technieken en technologie perfect toepassen om het beoogde resultaat te bereiken. \n\nWij doen aan Guerrillamarketing, het verzorgen van campagnes in klassieke en nieuwe media en efficiente Productreclame voor uw specifieke doelgroep. ', 'http://experienca.webnode.nl/', 4, 12, 'http://www.jellescheer.nl/logo/full/Logo_Experienca.png'),
(5, 'MENOKmedia', '- Maren Bom\n- Emily Dreijer\n- Naomi Drescher\n- Kelly Griffioen\n- Odile de Groot', 'Gemeente Leiden', 'Media bedrijfsjournalistiek', 'MENOKmedia is het initiatief van vijf jonge ondernemers in samenwerking met de hogeschool Leiden. MENOKmedia bruist van de energie en ideeen om iedere opdracht met beide handen aan te pakken en een prachtig resultaat af te leveren. \n\nMENOKmedia brengt bedrijf en media nader tot elkaar en helpt een organisatie het gewenste imago,identiteit en een grotere naamsbekendheid te verkrijgen d.m.v. diverse media, zowel online als offline.', 'http://menokmedia.wix.com/menokmedia', 8, 3, 'http://www.jellescheer.nl/logo/full/Logo_Menok_Media.jpg'),
(6, 'Peach PR', '- Madelon van der Hof\n- Megan Hoff\n- Eva Prins\n- Merle van Herk\n- Julia van Haaster', 'Unity FM', 'PR Bureau', 'Peach PR is een frisse onderneming die op een speelse en vernieuwende wijze naamsbekendheid voor onze klanten genereert. Met onze kennis van de maatschappelijke ontwikkelingen weten wij op een effectieve wijze contact te leggen met de doelgroep. \n\nDoor het inzetten van vernieuwende activiteiten op het gebied van guerrillamarketing, netwerken en online/offline promotie versterkt u het bereiken van de door u gestelde doelen.', 'http://peachpr.weebly.com/', 16, 3, 'http://www.jellescheer.nl/logo/full/Logo_PeachPR.png'),
(7, 'Remerkable', '- Annelotte Hofland\n- Joy Siemer\n- Raymond Malkoc\n- Stan van Meurs\n- Rogier Meel', 'Svets Information Services', 'Marketing & Reclame', 'Remerkable is een opvallend, divers en flexibel marketingbureau. Creativiteit en originaliteit staan centraal. Remerkable denkt verder dan out of the box. Met veel creatieve hersenpannen komen wij tot een goed idee. Wij zijn net als een hand, vijf verschillende vingers maar onmisbaar zonder elkaar. \n\nWij doen aan Merkwaarden, Promotie d.m.v. online marketing, mailings en sociale media campagnes, Design van logo''s, huisstijl, brochures en advertenties en Communicatie d.m.v. copywriting en grafische vormgeving. ', 'http://remerkable.weebly.com/', 111, 10, 'http://www.jellescheer.nl/logo/full/Logo_ReMERKable.png'),
(8, 'Ristretto', '- Laura van der Vliet\n- Roxanne Zobdeh\n- Esther Westerbeek\n- Milou Steen\n- Kristel van der  Stam', 'Area071', 'Merkadviesbureau', 'Ristretto is the new kid on the block op het gebied van merkadvies in Leiden. Ristretto is het sterkste kopje koffie op de markt en wordt puur gedronken. \n\nWij maken uw merk sterk. Zonder alle tierelantijntjes en versiersels. Ristretto bestaat uit vijf krachtige, ondernemende, leuke jongedames die sterk in hun schoenen staan. Ieder met haar eigen talenten.\n\nWij doen aan Merkonderzoek en op basis daarvan het ontwikkelen van een heldere strategie, Marketingcampagnes bedenken en uitvoeren, het verzorgen van beeldtaal en het uitvoeren van campagnes en activiteiten die uw merk sterker maken. ', 'http://ristrettobrands.nl', 73, 4, 'http://www.jellescheer.nl/logo/full/Logo_Ristretto.jpg'),
(9, 'Sound Marketing', '- Milou van Elleswijk\n- Dewi van Duijn\n- Merel Broekhuizen\n- Sara Bremer\n- Gijs van Dolder', 'Hutspop', 'Marketing & Communciatie', 'Sound Marketing is een betrouwbaar en creatief marketingcommunicatiebureau met een eigen geluid. Het bureau richt zich vooral op de online marketing en PR door middel van creatieve en effectieve communicatie.\n\nWij doen aan Internetmarketing; Online strategie, Conceptontwikkeling, Social Media, Relatiemanagement doelgroep, PR en Copywriting.', 'http://soundmarketing2014.wix.com/comon', 15, 2, 'http://www.jellescheer.nl/logo/full/Logo_SoundMarketing.png'),
(10, 'PR Bureau Spriet', '- Babette Vos\n- Karlijn van Krinpen\n- Vera Verschuur\n- Rowan Ven der Sterren\n- Priscilla Lodewijk', 'Esthetica Schoonheidssalon', 'PR en Communicatie', 'Spriet gebruikt een informele aanpak in het benaderen van haar klanten. Niet alleen om het de klant gemakkelijker te maken, maar ook om het haarzelf gemakkelijk te maken. \n\nSpriet kenmerkt zich als fris, Hollands en open-minded. Spriet gaat mee met de modernisering en technologie en speelt hierop in. Het Hollandse aspect staat voor de Nederlandse cultuur wat inhoud dat er een directe en nuchtere aanpak  wordt gehanteerd. Spriet is gespecialiseerd in PR.\n', 'http://www.prbureauspriet.jimdo.com', 13, 1, 'http://www.jellescheer.nl/logo/full/Logo_Spriet.jpg'),
(11, 'Streep Evenementenbureau', '- Cindy de Gilder\n- Rico van der Stede\n- Tobias Terpstra\n- Pinar Unlu\n- Marleen Vroman\n- Ferry van Wezop', 'PaulineAssisteert', 'Evenementenbureau', 'STREEP is een jong evenementenbureau dat zich richt op het organiseren van evenementen voor non-profit organisaties. STREEP richt zich op het organiseren van kleinschalige evenementen. STREEP staat bekend om haar creativiteit. Dit bureau is niet voor niets gespecialiseerd in het organiseren van originele themafeesten. \n\nVan planning tot aankleding, STREEP regelt het. STREEP organiseert evenementen in de provincies Noord-Holland, Zuid-Holland en Utrecht.', 'http://www.streepevents.com', 57, 1, 'http://www.jellescheer.nl/logo/full/Logo_Streep.png'),
(12, 'FEMOTION', '- Daphne Brough\n- Iris v. Geest\n- Iris Buys\n- Michelle v.der Tol\n- Wineke Cramer', 'Be Silk', 'PR en Promotiebureau', 'FEMOTION is een eenheid en bestaat uit vijf power vrouwen die strijden voor hetzelfde doel en resultaat.  Wij betrekken de klant bij het gehele (advies)proces. Hiermee onderscheiden wij onszelf van de andere PR- & promotiebureaus.\n\nFEMOTION is sociaal en maatschappelijk betrokken met wat er in de wereld gebeurt. Het is belangrijk om te weten welke trends er nu en in de toekomst (zullen) zijn, daar spelen wij als bureau op in. FEMOTION doet aan Social Media, Promotie en aan het schrijven van teksten. ', 'http://femotion.weebly.com/', 43, 1, 'http://www.jellescheer.nl/logo/full/Logo_Femotion.png'),
(13, 'Fresh Events', '- Maaikedirkje Cornelissen\n- Jhemyla van Es\n- Jaimy de Roo\n- Lisa Salomons\n- Laura Berlijn', 'BPlusC / Centrum voor Amateurkunst', 'Evenementenbureau', 'Geen beschrijving', 'https://www.facebook.com/fresheventsleiden', 127, 1, 'http://www.jellescheer.nl/logo/full/Logo_FreshEvents.png'),
(14, 'Goodfellas', '- Amier Baker\n- Rens de Wit\n- Mitchel de Bruin\n- Jeroen van Bilderbeek\n- Darrick Vianen', 'Leids Lekkers (Mieke van Ulden)', 'Marketing & Communicatie', 'Goodfellas levert inzicht, vormgeving en uitvoering van media en marketing van bedrijven, waarbij het uitvoeren van evenementen een specialiteit van Goodfellas is. \n\nGoodfellas kan worden ingehuurd voor het verbeteren van marketing-, en media-uitingen en het werken aan nieuwe inzichten en mogelijkheden. \n\nWij zijn interessant voor grotere bedrijven, die op zoek zijn naar  nieuwe en frisse manieren van het uitvoeren van communicatieve uitingen. Goodfellas denkt niet in beperkingen maar in mogelijkheden.\n', 'http://goodfellas-communication.weebly.com/', 91, 2, 'http://www.jellescheer.nl/logo/full/Logo_Goodfellas.png'),
(15, 'Gutenberg & Coster', '- Manouk Gunter\n- Jeanne Kinders\n- Frank Joosten\n- Jip Janssen\n- Alwin Janse de Jonge', 'Gordijn Aannemersbedrijf', 'Communicatieadviesbureau', 'Gutenberg & Coster onderscheidt zich op meerdere manieren van andere communicatieadviesbureaus. Allereerst zijn wij een gemengd bedrijf dat bestaat uit mannen en vrouwen. Wij denken dus vanuit een mannelijk en vrouwelijk perspectief. \n\nWij zijn een jong, maar serieus adviesbureau dat professioneel te werk gaat. Gutenberg & Coster richt zich vooral op de business-to-businessmarkt. Wij zijn gespecialiseerd op online en offline gebied. \n\nOok is Gutenberg & Coster een heel persoonlijk bedrijf dat altijd advies op maat levert. Wij zorgen voor concrete oplossingen en een hoge kwaliteit. Een ander speerpunt van Gutenberg & Coster is creativiteit. Dat wil zeggen dat wij goed zijn in het bedenken van nieuwe uitingen in beeld en schrift. Dit vult onze andere specialisatie perfect aan.', 'http://gutenbergcoster.weebly.com/', 14, 1, 'http://www.jellescheer.nl/logo/full/Logo_Gutenberg&Coster.jpg'),
(16, 'The Inspiration Factory', '- Mitchel Bil\n- Birgit Dekker\n- Jesper Berg\n- Marthe Philipsen\n- Annabel Kamermans\n- Kevin Crins', 'Stichting Present', 'Communicatieadviesbureau', 'The Inspiration Factory is nog geen officiele onderneming. The Inspiration Factory wordt momenteel gerund door  tweedejaarsstudenten Communicatie van Hogeschool Leiden. The Inspiration Factory is opgericht in het kader van ComOn, een werk leerperiode op deze hogeschool.\n\nThe Inspiration Factory biedt advies op maat in communicatieland. The Inspiration Factory geeft bijvoorbeeld advies op het gebied van communicatiemiddelen inzetten zoals social media, identiteit en imagokwesties, interne en of corporate communicatie, marketingcommunicatie en entrepeneurship. The Inspiration Factory doet en of assisteert zelfs bij de praktische uitvoering van zijn adviezen.', 'http://crins90.wix.com/inspiration#!team/citg', 2, 6, 'http://www.jellescheer.nl/logo/full/Logo_TheInspirationFactory.png'),
(17, 'Wij voor jullie', '- Matthijs van der Veld\n- Danielle Moerland\n- Clenda Moen\n- Kristen Papadopoulos\n- Laura Sjardin', 'Vincentius Hof', 'Corporate Communicatie', 'Wij is ontstaan door vijf studenten van de hogeschool Leiden. Deze studenten werken aan een project genaamd ComOn, waarbij deze studenten een fictief bedrijf opzetten.\n\nDe opdrachtgevers die de hogeschool heeft uitgekozen, hebben opdrachten door de studenten klaarstaan. Op de ComOn markt kiezen deze bedrijven een fictief bedrijf en daarbij hopelijk voor het ambitieuze, passievolle, gemotiveerde bedrijf Wij. Wij van Wij doen aan Managementorganisatie, Marketingcommunicatie en Organisatiecommunicatie', 'http://wijvoorjullie.wordpress.com/', 1337, 2, 'http://www.jellescheer.nl/logo/full/Logo_WijVoorJullie.jpg');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
